### ISSUE TITLE
CocoaPods could not find compatible versions for pod "KOLocalizedString":   In Podfile:     KOLocalizedString (~> 0.0.3)

### ISSUE THREAD

**Issue by karthickkck315** [SethSky/KOLocalizedString#10]
i can't install pod file in my latest version xcode9.2 swift 4.0
[!] CocoaPods could not find compatible versions for pod "KOLocalizedString":
  In Podfile:
    KOLocalizedString (~> 0.0.3)

Specs satisfying the `KOLocalizedString (~> 0.0.3)` dependency were found, but they required a higher minimum deployment target.

Please help.....

**Comment by SethSky** [comment]
Maybe you will help version (~> 0.0.4).
